@startuml ユースケース図
left to right direction

actor ユーザー

rectangle "web訪問者システム" {
  ユーザー -- (新規登録ができる)
  ユーザー -- (ログインできる)
  ユーザー -- (自分と他の訪問者情報を参照することができる)
  ユーザー -- (自分の登録情報を変更できる)
  ユーザー -- (自分の登録情報を削除できる)
  ユーザー -- (ログアウトできる)

}

@enduml